---

- hosts: all
  gather_facts: True

#---------------------------------------
# Consul Servers
#---------------------------------------

- hosts: consul-servers
  become: yes
  roles:
    - role: consul
      # force: yes

#---------------------------------------
# Consul Clients
#---------------------------------------

- hosts: consul-clients
  become: yes
  roles:
    - role: consul
      service_name: "{{ inventory_service_name }}"
      mode: client
      # force: yes
